### ISSUE TITLE
Could not find module @webex/components

### ISSUE THREAD

**Issue by nikvitaldusharov** [webex/components#140]
After installation  @webex/components module I could not build my application. I am getting this issue - Could not find module @webex/components. I've checked package.json file for this module. There is no main section now, and also no index.js file in the installed folder. Looks like an issue.

**Comment by lalli-flores** [comment]
Can you check your project configuration? I don't see anything wrong in the [latest published `package.json`](https://unpkg.com/browse/@webex/components@1.45.3/package.json) and all [distribution files](https://unpkg.com/browse/@webex/components@1.45.3/) seem to be right.

There is no main section because we use [`browser`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#browser) and [`module`](https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module) since we use ES6.

**Comment by nikvitaldusharov** [comment]
@lalli-flores You had both main and module in previous versions (maybe till 1.42.3). Looks like I need to change my project configuration now. Thank you.

**Comment by lalli-flores** [comment]
@nikvitaldusharov, you're right, we used to have `main` but decided to use `browser` instead since components are meant to use in the browser exclusively (as it is UI).
